### ISSUE TITLE
Either add jslint rules or start adding semicolumn after each statement

### ISSUE THREAD

**Issue by kirillrdy** [arcarson/palette-generator#3]

**Comment by kirillrdy** [comment]
You could have replied here :-)

anyways. i should have provided steps to reproduce
npm install eslint --save-dev
./node_modules/.bin/eslinit --init
i prefer aribnb style, but google one is also pretty good ( with bigger emphasis on documentation )

then
./node_modules/.bin/eslint src/palette_generator.js

Im sure vim would have lots of good plugins that integrate well with eslint

:beer:

**Comment by arcarson** [comment]
![screen shot 2016-08-16 at 7 22 55 am](https://cloud.githubusercontent.com/assets/735565/17680227/7cdf66f6-6382-11e6-9ee3-49ec6d1e8b21.png)
😱

**Comment by kirillrdy** [comment]
You don't have to follow all of their styles. 
Most of it is very useful though

**Comment by arcarson** [comment]
Done!
